/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pml.InterfaceGrafica;

import javax.swing.JComboBox;
import com.pml.Configuracoes.ConfigIndicadores;

/**
 *
 * @author Felipe Mattos
 */
public class IG_Indicadores extends javax.swing.JFrame {

    /**
     * Creates new form IG_Indicadores
     */
    public IG_Indicadores() {
        initComponents();
        
        jTemIndGen.setSelected(ConfigIndicadores.isTemGen());
        jIndGenOpe.setSelectedIndex(retornaSelecao(jIndGenOpe, ConfigIndicadores.getGenOpe()));
        jIndGenValor1.setText(String.valueOf(ConfigIndicadores.getGenVal1()));
        jIndGenValor2.setText(String.valueOf(ConfigIndicadores.getGenVal2()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTemIndGen = new javax.swing.JCheckBox();
        jIndGenOpe = new javax.swing.JComboBox<>();
        jIndGenValor1 = new javax.swing.JFormattedTextField();
        jIndGenValor2 = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Indicadores Diarios");

        jTemIndGen.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTemIndGen.setText("Indicador[D-1]:");
        jTemIndGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verificaIndicadores(evt);
            }
        });

        jIndGenOpe.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jIndGenOpe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ">", "<", "=", "contido" }));
        jIndGenOpe.setEnabled(false);
        jIndGenOpe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verificaIndicadores(evt);
            }
        });

        jIndGenValor1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jIndGenValor1.setText("0");
        jIndGenValor1.setEnabled(false);
        jIndGenValor1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jIndGenValor1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jIndGenValor1verificaTecla_Neg(evt);
            }
        });

        jIndGenValor2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jIndGenValor2.setText("0");
        jIndGenValor2.setEnabled(false);
        jIndGenValor2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jIndGenValor2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jIndGenValor2verificaTecla_Neg(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("e");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Aplicar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTemIndGen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jIndGenOpe, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jIndGenValor1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jIndGenValor2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTemIndGen)
                    .addComponent(jIndGenOpe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jIndGenValor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jIndGenValor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jIndGenValor1verificaTecla_Neg(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jIndGenValor1verificaTecla_Neg
        char enter = evt.getKeyChar();
        if(enter == ',' || enter == '-')
        return;
        if(!(Character.isDigit(enter)))
        evt.consume();
    }//GEN-LAST:event_jIndGenValor1verificaTecla_Neg

    private void jIndGenValor2verificaTecla_Neg(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jIndGenValor2verificaTecla_Neg
        char enter = evt.getKeyChar();
        if(enter == ',' || enter == '-')
        return;
        if(!(Character.isDigit(enter)))
        evt.consume();
    }//GEN-LAST:event_jIndGenValor2verificaTecla_Neg

    private void verificaIndicadores(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verificaIndicadores
        if(jTemIndGen.isSelected()){
            jIndGenValor1.setEnabled(true);
            jIndGenOpe.setEnabled(true);
            if(jIndGenOpe.getSelectedIndex()==3)
            jIndGenValor2.setEnabled(true);
            else{
                jIndGenValor2.setEnabled(false);
                jIndGenValor2.setText("0");
            }

        }else{
            jIndGenOpe.setEnabled(false);
            jIndGenValor1.setEnabled(false);
            jIndGenValor1.setText("0");
            jIndGenValor2.setEnabled(false);
            jIndGenValor2.setText("0");
        }
    }//GEN-LAST:event_verificaIndicadores

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        float
        indGenValor1 = Float.valueOf(jIndGenValor1.getText().replace(',', '.')),
        indGenValor2 = Float.valueOf(jIndGenValor2.getText().replace(',', '.'));

        boolean
        temIndGen = jTemIndGen.isSelected();
        

        String
        indGenOper = jIndGenOpe.getItemAt(jIndGenOpe.getSelectedIndex()).toLowerCase();
        ConfigIndicadores.setGen(temIndGen, indGenOper, indGenValor1, indGenValor2);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    static javax.swing.JComboBox<String> jIndGenOpe;
    static javax.swing.JFormattedTextField jIndGenValor1;
    static javax.swing.JFormattedTextField jIndGenValor2;
    private javax.swing.JLabel jLabel12;
    static javax.swing.JCheckBox jTemIndGen;
    // End of variables declaration//GEN-END:variables

    /**
     * Busca no comboBox a string informada e retorna a posição
     * @return 
     */
    private int retornaSelecao(JComboBox comboBox, String selecao){
        selecao = selecao.toLowerCase();
        for(int i =0; i < comboBox.getItemCount(); i++){
            if(comboBox.getItemAt(i).toString().equals(selecao))
                return i;
        }
        return 0;
    }


}
