/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pml.InterfaceGrafica;

import javax.swing.JComboBox;
import com.pml.Configuracoes.ConfigIndicadores;
import javax.swing.JOptionPane;

/**
 *
 * @author Felipe Mattos
 */
public class IG_IndicadoresDiario extends javax.swing.JFrame {

    /**
     * Creates new form IG_Indicadores
     */
    public IG_IndicadoresDiario() {
        initComponents();
        
        jTemIndFechAbe.setSelected(ConfigIndicadores.isTemFechAbe());
        jTemIndGen.setSelected(ConfigIndicadores.isTemGen());
        jTemDirInd.setSelected(ConfigIndicadores.isTemDirInd());
        jTemAbeFech.setSelected(ConfigIndicadores.isTemAbeFech());

        jIndFechAbeOpe.setSelectedIndex(retornaSelecao(jIndFechAbeOpe, ConfigIndicadores.getFechAbeOpe()));
        jIndGenOpe.setSelectedIndex(retornaSelecao(jIndGenOpe, ConfigIndicadores.getGenOpe()));
        jDirIndOpe.setSelectedIndex(retornaSelecao(jDirIndOpe, ConfigIndicadores.getDirOpe()));
        jAbeFechOpe.setSelectedIndex(retornaSelecao(jAbeFechOpe, ConfigIndicadores.getAbeFechOpe()));

        jIndFechAbeValor1.setText(String.valueOf(ConfigIndicadores.getFechAbeVal1()));
        jIndFechAbeValor2.setText(String.valueOf(ConfigIndicadores.getFechAbeVal2()));
        jIndDirIndValor1.setText(String.valueOf(ConfigIndicadores.getDirVal1()));
        jIndDirIndValor2.setText(String.valueOf(ConfigIndicadores.getDirVal2()));
        jIndAbeFechValor1.setText(String.valueOf(ConfigIndicadores.getAbeFechVal1()));
        jIndAbeFechValor2.setText(String.valueOf(ConfigIndicadores.getAbeFechVal2()));
        jIndGenValor1.setText(String.valueOf(ConfigIndicadores.getGenVal1()));
        jIndGenValor2.setText(String.valueOf(ConfigIndicadores.getGenVal2()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        jTemIndFechAbe = new javax.swing.JCheckBox();
        jIndFechAbeOpe = new javax.swing.JComboBox<>();
        jTemIndGen = new javax.swing.JCheckBox();
        jIndFechAbeValor1 = new javax.swing.JFormattedTextField();
        jTemDirInd = new javax.swing.JCheckBox();
        jIndFechAbeValor2 = new javax.swing.JFormattedTextField();
        jTemAbeFech = new javax.swing.JCheckBox();
        jIndDirIndValor1 = new javax.swing.JFormattedTextField();
        jIndGenOpe = new javax.swing.JComboBox<>();
        jIndDirIndValor2 = new javax.swing.JFormattedTextField();
        jDirIndOpe = new javax.swing.JComboBox<>();
        jIndAbeFechValor1 = new javax.swing.JFormattedTextField();
        jAbeFechOpe = new javax.swing.JComboBox<>();
        jIndAbeFechValor2 = new javax.swing.JFormattedTextField();
        jIndGenValor1 = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        jIndGenValor2 = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTemAbeInd = new javax.swing.JCheckBox();
        jAbeIndOpe = new javax.swing.JComboBox<>();
        jIndAbeIndValor1 = new javax.swing.JFormattedTextField();
        jIndAbeIndValor2 = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Indicadores Diarios");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("e");

        jTemIndFechAbe.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTemIndFechAbe.setText("Abe[D-1] --> Fech[D-1]");
        jTemIndFechAbe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verificaIndicadores(evt);
            }
        });

        jIndFechAbeOpe.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jIndFechAbeOpe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ">", "<", "=", "contido" }));
        jIndFechAbeOpe.setEnabled(false);
        jIndFechAbeOpe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verificaIndicadores(evt);
            }
        });

        jTemIndGen.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTemIndGen.setText("Indicador[D-1]:");
        jTemIndGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verificaIndicadores(evt);
            }
        });

        jIndFechAbeValor1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jIndFechAbeValor1.setText("0");
        jIndFechAbeValor1.setEnabled(false);
        jIndFechAbeValor1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jIndFechAbeValor1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jIndFechAbeValor1verificaTecla_Neg(evt);
            }
        });

        jTemDirInd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTemDirInd.setText("Indicador[D-2] --> Indicador[D-1]");
        jTemDirInd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verificaIndicadores(evt);
            }
        });

        jIndFechAbeValor2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jIndFechAbeValor2.setText("0");
        jIndFechAbeValor2.setEnabled(false);
        jIndFechAbeValor2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jIndFechAbeValor2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jIndFechAbeValor2verificaTecla_Neg(evt);
            }
        });

        jTemAbeFech.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTemAbeFech.setText("Fech[D-1] --> Abe[D-0]");
        jTemAbeFech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verificaIndicadores(evt);
            }
        });

        jIndDirIndValor1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jIndDirIndValor1.setText("0");
        jIndDirIndValor1.setEnabled(false);
        jIndDirIndValor1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jIndDirIndValor1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jIndDirIndValor1verificaTecla_Neg(evt);
            }
        });

        jIndGenOpe.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jIndGenOpe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ">", "<", "=", "contido" }));
        jIndGenOpe.setEnabled(false);
        jIndGenOpe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verificaIndicadores(evt);
            }
        });

        jIndDirIndValor2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jIndDirIndValor2.setText("0");
        jIndDirIndValor2.setEnabled(false);
        jIndDirIndValor2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jIndDirIndValor2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jIndDirIndValor2verificaTecla_Neg(evt);
            }
        });

        jDirIndOpe.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jDirIndOpe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ">", "<", "=", "contido" }));
        jDirIndOpe.setEnabled(false);
        jDirIndOpe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verificaIndicadores(evt);
            }
        });

        jIndAbeFechValor1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jIndAbeFechValor1.setText("0");
        jIndAbeFechValor1.setEnabled(false);
        jIndAbeFechValor1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jIndAbeFechValor1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jIndAbeFechValor1verificaTecla_Neg(evt);
            }
        });

        jAbeFechOpe.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jAbeFechOpe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ">", "<", "=", "contido" }));
        jAbeFechOpe.setEnabled(false);
        jAbeFechOpe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verificaIndicadores(evt);
            }
        });

        jIndAbeFechValor2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jIndAbeFechValor2.setText("0");
        jIndAbeFechValor2.setEnabled(false);
        jIndAbeFechValor2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jIndAbeFechValor2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jIndAbeFechValor2verificaTecla_Neg(evt);
            }
        });

        jIndGenValor1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jIndGenValor1.setText("0");
        jIndGenValor1.setEnabled(false);
        jIndGenValor1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jIndGenValor1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jIndGenValor1verificaTecla_Neg(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("e");

        jIndGenValor2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jIndGenValor2.setText("0");
        jIndGenValor2.setEnabled(false);
        jIndGenValor2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jIndGenValor2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jIndGenValor2verificaTecla_Neg(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("e");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("e");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Aplicar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTemAbeInd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTemAbeInd.setText("Indicador[D-1] --> Abe[D-0]");
        jTemAbeInd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verificaIndicadores(evt);
            }
        });

        jAbeIndOpe.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jAbeIndOpe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ">", "<", "=", "contido" }));
        jAbeIndOpe.setEnabled(false);
        jAbeIndOpe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verificaIndicadores(evt);
            }
        });

        jIndAbeIndValor1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jIndAbeIndValor1.setText("0");
        jIndAbeIndValor1.setEnabled(false);
        jIndAbeIndValor1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jIndAbeIndValor1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jIndAbeIndValor1verificaTecla_Neg(evt);
            }
        });

        jIndAbeIndValor2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jIndAbeIndValor2.setText("0");
        jIndAbeIndValor2.setEnabled(false);
        jIndAbeIndValor2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jIndAbeIndValor2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jIndAbeIndValor2verificaTecla_Neg(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("e");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTemIndFechAbe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTemDirInd)
                            .addComponent(jTemIndGen)
                            .addComponent(jTemAbeFech))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jIndFechAbeOpe, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jIndGenOpe, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDirIndOpe, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jAbeFechOpe, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jIndGenValor1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jIndGenValor2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jIndFechAbeValor1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jIndFechAbeValor2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jIndDirIndValor1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jIndDirIndValor2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jIndAbeFechValor1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jIndAbeFechValor2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTemAbeInd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jAbeIndOpe, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jIndAbeIndValor1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jIndAbeIndValor2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTemIndGen)
                    .addComponent(jIndGenOpe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jIndGenValor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jIndGenValor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTemIndFechAbe)
                    .addComponent(jIndFechAbeOpe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jIndFechAbeValor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jIndFechAbeValor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jIndDirIndValor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jIndDirIndValor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jDirIndOpe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTemDirInd)))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jIndAbeFechValor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jIndAbeFechValor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTemAbeFech)
                        .addComponent(jAbeFechOpe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jIndAbeIndValor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jIndAbeIndValor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTemAbeInd)
                        .addComponent(jAbeIndOpe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jIndGenValor1verificaTecla_Neg(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jIndGenValor1verificaTecla_Neg
        char enter = evt.getKeyChar();
        if(enter == ',' || enter == '-')
        return;
        if(!(Character.isDigit(enter)))
        evt.consume();
    }//GEN-LAST:event_jIndGenValor1verificaTecla_Neg

    private void jIndGenValor2verificaTecla_Neg(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jIndGenValor2verificaTecla_Neg
        char enter = evt.getKeyChar();
        if(enter == ',' || enter == '-')
        return;
        if(!(Character.isDigit(enter)))
        evt.consume();
    }//GEN-LAST:event_jIndGenValor2verificaTecla_Neg

    private void jIndFechAbeValor1verificaTecla_Neg(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jIndFechAbeValor1verificaTecla_Neg
        char enter = evt.getKeyChar();
        if(enter == ',' || enter == '-')
        return;
        if(!(Character.isDigit(enter)))
        evt.consume();
    }//GEN-LAST:event_jIndFechAbeValor1verificaTecla_Neg

    private void jIndFechAbeValor2verificaTecla_Neg(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jIndFechAbeValor2verificaTecla_Neg
        char enter = evt.getKeyChar();
        if(enter == ',' || enter == '-')
        return;
        if(!(Character.isDigit(enter)))
        evt.consume();
    }//GEN-LAST:event_jIndFechAbeValor2verificaTecla_Neg

    private void jIndDirIndValor1verificaTecla_Neg(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jIndDirIndValor1verificaTecla_Neg
        char enter = evt.getKeyChar();
        if(enter == ',' || enter == '-')
        return;
        if(!(Character.isDigit(enter)))
        evt.consume();
    }//GEN-LAST:event_jIndDirIndValor1verificaTecla_Neg

    private void jIndDirIndValor2verificaTecla_Neg(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jIndDirIndValor2verificaTecla_Neg
        char enter = evt.getKeyChar();
        if(enter == ',' || enter == '-')
        return;
        if(!(Character.isDigit(enter)))
        evt.consume();
    }//GEN-LAST:event_jIndDirIndValor2verificaTecla_Neg

    private void jIndAbeFechValor1verificaTecla_Neg(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jIndAbeFechValor1verificaTecla_Neg
        char enter = evt.getKeyChar();
        if(enter == ',' || enter == '-')
        return;
        if(!(Character.isDigit(enter)))
        evt.consume();
    }//GEN-LAST:event_jIndAbeFechValor1verificaTecla_Neg

    private void jIndAbeFechValor2verificaTecla_Neg(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jIndAbeFechValor2verificaTecla_Neg
        char enter = evt.getKeyChar();
        if(enter == ',' || enter == '-')
        return;
        if(!(Character.isDigit(enter)))
        evt.consume();
    }//GEN-LAST:event_jIndAbeFechValor2verificaTecla_Neg

    private void verificaIndicadores(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verificaIndicadores
        if(jTemAbeFech.isSelected()){
            jIndAbeFechValor1.setEnabled(true);
            jAbeFechOpe.setEnabled(true);
            if(jAbeFechOpe.getSelectedIndex()==3)
            jIndAbeFechValor2.setEnabled(true);
            else{
                jIndAbeFechValor2.setEnabled(false);
                jIndAbeFechValor2.setText("0");
            }

        }else{
            jAbeFechOpe.setEnabled(false);
            jIndAbeFechValor1.setEnabled(false);
            jIndAbeFechValor1.setText("0");
            jIndAbeFechValor2.setEnabled(false);
            jIndAbeFechValor2.setText("0");
        }

        if(jTemDirInd.isSelected()){
            jIndDirIndValor1.setEnabled(true);
            jDirIndOpe.setEnabled(true);
            if(jDirIndOpe.getSelectedIndex()==3)
            jIndDirIndValor2.setEnabled(true);
            else{
                jIndDirIndValor2.setEnabled(false);
                jIndDirIndValor2.setText("0");
            }

        }else{
            jDirIndOpe.setEnabled(false);
            jIndDirIndValor1.setEnabled(false);
            jIndDirIndValor1.setText("0");
            jIndDirIndValor2.setEnabled(false);
            jIndDirIndValor2.setText("0");
        }

        if(jTemIndFechAbe.isSelected()){
            jIndFechAbeValor1.setEnabled(true);
            jIndFechAbeOpe.setEnabled(true);
            if(jIndFechAbeOpe.getSelectedIndex()==3)
            jIndFechAbeValor2.setEnabled(true);
            else{
                jIndFechAbeValor2.setEnabled(false);
                jIndFechAbeValor2.setText("0");
            }

        }else{
            jIndFechAbeOpe.setEnabled(false);
            jIndFechAbeValor1.setEnabled(false);
            jIndFechAbeValor1.setText("0");
            jIndFechAbeValor2.setEnabled(false);
            jIndFechAbeValor2.setText("0");
        }

        if(jTemIndGen.isSelected()){
            jIndGenValor1.setEnabled(true);
            jIndGenOpe.setEnabled(true);
            if(jIndGenOpe.getSelectedIndex()==3)
            jIndGenValor2.setEnabled(true);
            else{
                jIndGenValor2.setEnabled(false);
                jIndGenValor2.setText("0");
            }

        }else{
            jIndGenOpe.setEnabled(false);
            jIndGenValor1.setEnabled(false);
            jIndGenValor1.setText("0");
            jIndGenValor2.setEnabled(false);
            jIndGenValor2.setText("0");
        }
        
        if(jTemAbeInd.isSelected()){
            jIndAbeIndValor1.setEnabled(true);
            jAbeIndOpe.setEnabled(true);
            if(jAbeIndOpe.getSelectedIndex()==3)
            jIndAbeIndValor2.setEnabled(true);
            else{
                jIndAbeIndValor2.setEnabled(false);
                jIndAbeIndValor2.setText("0");
            }

        }else{
            jAbeIndOpe.setEnabled(false);
            jIndAbeIndValor1.setEnabled(false);
            jIndAbeIndValor1.setText("0");
            jIndAbeIndValor2.setEnabled(false);
            jIndAbeIndValor2.setText("0");
        }
    }//GEN-LAST:event_verificaIndicadores

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        float
        indGenValor1 = Float.valueOf(jIndGenValor1.getText().replace(',', '.')),
        indGenValor2 = Float.valueOf(jIndGenValor2.getText().replace(',', '.')),
        indFechAbeValor1 = Float.valueOf(jIndFechAbeValor1.getText().replace(',', '.')),
        indFechAbeValor2 = Float.valueOf(jIndFechAbeValor2.getText().replace(',', '.')),
        indDirIndValor1 = Float.valueOf(jIndDirIndValor1.getText().replace(',', '.')),
        indDirIndValor2 = Float.valueOf(jIndDirIndValor2.getText().replace(',', '.')),
        indAbeFechValor1 = Float.valueOf(jIndAbeFechValor1.getText().replace(',', '.')),
        indAbeFechValor2 = Float.valueOf(jIndAbeFechValor2.getText().replace(',', '.')),
        indAbeIndValor1 = Float.valueOf(jIndAbeIndValor1.getText().replace(',', '.')),
        indAbeIndValor2 = Float.valueOf(jIndAbeIndValor2.getText().replace(',', '.'));

        boolean
        temIndGen = jTemIndGen.isSelected(),
        temIndFechAbe = jTemIndFechAbe.isSelected(),
        temDirInd = jTemDirInd.isSelected(),
        temAbeFech = jTemAbeFech.isSelected(),
        temAbeInd = jTemAbeInd.isSelected();
        

        String
        indGenOper = jIndGenOpe.getItemAt(jIndGenOpe.getSelectedIndex()).toLowerCase(),
        indFechAbeOper = jIndFechAbeOpe.getItemAt(jIndFechAbeOpe.getSelectedIndex()).toLowerCase(),
        indDirIndOper = jDirIndOpe.getItemAt(jDirIndOpe.getSelectedIndex()).toLowerCase(),
        indAbeFechOper = jAbeFechOpe.getItemAt(jAbeFechOpe.getSelectedIndex()).toLowerCase(),
        indAbeIndOper = jAbeIndOpe.getItemAt(jAbeIndOpe.getSelectedIndex()).toLowerCase();

        ConfigIndicadores.setGen(temIndGen, indGenOper, indGenValor1, indGenValor2);
        ConfigIndicadores.setFechAbe(temIndFechAbe, indFechAbeOper, indFechAbeValor1, indFechAbeValor2);
        ConfigIndicadores.setDirInd(temDirInd, indDirIndOper, indDirIndValor1, indDirIndValor2);
        ConfigIndicadores.setAbeFech(temAbeFech, indAbeFechOper, indAbeFechValor1, indAbeFechValor2);
        ConfigIndicadores.setAbeInd(temAbeInd, indAbeIndOper, indAbeIndValor1, indAbeIndValor2);
        JOptionPane.showMessageDialog(null, "Valores Registrados");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jIndAbeIndValor1verificaTecla_Neg(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jIndAbeIndValor1verificaTecla_Neg
        // TODO add your handling code here:
    }//GEN-LAST:event_jIndAbeIndValor1verificaTecla_Neg

    private void jIndAbeIndValor2verificaTecla_Neg(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jIndAbeIndValor2verificaTecla_Neg
        // TODO add your handling code here:
    }//GEN-LAST:event_jIndAbeIndValor2verificaTecla_Neg

    // Variables declaration - do not modify//GEN-BEGIN:variables
    static javax.swing.JComboBox<String> jAbeFechOpe;
    static javax.swing.JComboBox<String> jAbeIndOpe;
    private javax.swing.JButton jButton1;
    static javax.swing.JComboBox<String> jDirIndOpe;
    static javax.swing.JFormattedTextField jIndAbeFechValor1;
    static javax.swing.JFormattedTextField jIndAbeFechValor2;
    static javax.swing.JFormattedTextField jIndAbeIndValor1;
    static javax.swing.JFormattedTextField jIndAbeIndValor2;
    static javax.swing.JFormattedTextField jIndDirIndValor1;
    static javax.swing.JFormattedTextField jIndDirIndValor2;
    static javax.swing.JComboBox<String> jIndFechAbeOpe;
    static javax.swing.JFormattedTextField jIndFechAbeValor1;
    static javax.swing.JFormattedTextField jIndFechAbeValor2;
    static javax.swing.JComboBox<String> jIndGenOpe;
    static javax.swing.JFormattedTextField jIndGenValor1;
    static javax.swing.JFormattedTextField jIndGenValor2;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    static javax.swing.JCheckBox jTemAbeFech;
    static javax.swing.JCheckBox jTemAbeInd;
    static javax.swing.JCheckBox jTemDirInd;
    static javax.swing.JCheckBox jTemIndFechAbe;
    static javax.swing.JCheckBox jTemIndGen;
    // End of variables declaration//GEN-END:variables

    /**
     * Busca no comboBox a string informada e retorna a posição
     * @return 
     */
    private int retornaSelecao(JComboBox comboBox, String selecao){
        selecao = selecao.toLowerCase();
        for(int i =0; i < comboBox.getItemCount(); i++){
            if(comboBox.getItemAt(i).toString().equals(selecao))
                return i;
        }
        return 0;
    }


}
